---
title: "Practice 5.1 leaflet package"
output: html_document
date: "2022-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(maptools)
library(rgdal)
library (sp)
library(raster)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(rgbif)
library(mapr)
library(marmap)
library(leaflet)
library(dplyr)
library(rjson)
library(jsonlite)
library(RCurl)
library(tidyverse)
library(htmltools)
```


## **A Simple Interactive Map**

Here, I've made a simple interactive map of my home in the Philippines. (I miss home... since I haven't gone back in almost 3 years.)

```{r echo=TRUE}
HOME<- paste(sep = "</br>", 
             "<b><p> No place like HOME &#128151;</p></b>")
                 
PHL<- rgdal::readOGR ("/Users/shinjean/Documents/ClassR/R/gadm41_PHL_1.json")

Phl<- leaflet(PHL)%>%
  setView(lng=120.5909532, lat=16.3863067, zoom=7)%>%
  addPopups(120.5909532,16.3863067, HOME, options= popupOptions 
            (closeButton=FALSE, keepInView = TRUE, closeOnClick = NULL))%>%
  addPolygons(stroke= TRUE, color="#2d551b", smoothFactor= 1, opacity= 0.3 )%>%
  addTiles() %>% 
  addRectangles (lng1= 120.58871, lat1= 16.38797,lng2= 120.59317, lat2= 16.38483,color= "#ffa500",fillColor= "#ffa500", fillOpacity = 0.2)%>%
  addScaleBar(
    position = "bottomright",
    options = scaleBarOptions(maxWidth = 100, metric = TRUE,imperial = TRUE))

Phl
```



